[package]
name = "granite2"
version = "0.1.0"
description = "Find Deadlocks in Rust code with Petri net model checking"
repository = "https://github.com/hlisdero/Granite2"
homepage = "https://github.com/hlisdero/Granite2"
authors = ["Horacio Lisdero Scaffino <hlisdero@users.noreply.github.com>"]
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["petri-net", "deadlock-detection", "rustc-plugin"]
categories = ["command-line-utilities"]
edition = "2021"

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
netcrab = { path = "../netcrab" }

[dev-dependencies]
assert_cmd = "2.0.7"
assert_fs = "1.0.10"
predicates = "2.1.4"

[package.metadata.rust-analyzer]
# This package uses #[feature(rustc_private)]
rustc_private = true