[package]
name = "cargo-check-deadlock"
version = "1.0.0"
description = "Find Deadlocks in Rust code with Petri net model checking"
repository = "https://github.com/hlisdero/cargo-check-deadlock"
homepage = "https://github.com/hlisdero/cargo-check-deadlock"
authors = ["Horacio Lisdero Scaffino <hlisdero@users.noreply.github.com>"]
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["petri-net", "deadlock-detection", "rustc-plugin"]
categories = ["command-line-utilities"]
edition = "2021"

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
clap-verbosity-flag = "2.0.0"
env_logger = "0.10.0"
log = "0.4.17"
netcrab = "1.0.0"

[dev-dependencies]
assert_cmd = "2.0.8"
assert_fs = "1.0.10"
predicates = "3.0.2"

[package.metadata.rust-analyzer]
# This package uses #[feature(rustc_private)]
rustc_private = true
