on: [push, pull_request]

name: Continuous integration

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions-rust-lang/setup-rust-toolchain@v1.14.1
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions-rust-lang/setup-rust-toolchain@v1.14.1
        with:
          components: rustfmt
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions-rust-lang/setup-rust-toolchain@v1.14.1
        with:
          components: clippy
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: clippy
          args: -- -Dclippy::pedantic -Dclippy::suspicious -Dclippy::nursery -Dclippy::complexity -Dclippy::perf -Dclippy::cargo
